server:
    port: 9090
    context-path: /

logging:
    level:
        tk.mybatis: TRACE

druid:
    url: jdbc:mysql://10.2.14.105/test
    username: root
    password: buaanlsde
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true


mybatis:
    type-aliases-package: buaa.eos.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - buaa.eos.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql